formatting:
  active: true
  android: false
  autoCorrect: true
  PackageName:
    active: false
    autoCorrect: false
  NoWildcardImports:
    active: false

naming:
  active: true
  PackageNaming:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    packagePattern: '[a-z]+(_[A-Za-z0-9]+)*(\.[a-z]+(_[A-Za-z0-9]+)*)*'

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false